"""RustCrypto slh-dsa (FIPS 205) binding. Keys and signatures are FIPS 205 byte encodings; the
parameter set is its FIPS 205 name, for example "SLH-DSA-SHA2-128f"."""

def parameter_sets() -> list[str]: ...
def keygen(parameter_set: str) -> tuple[bytes, bytes]: ...
def keygen_internal(
    parameter_set: str, sk_seed: bytes, sk_prf: bytes, pk_seed: bytes
) -> tuple[bytes, bytes]: ...
def sign(
    parameter_set: str,
    sk: bytes,
    message: bytes,
    context: bytes = b"",
    rand: bytes | None = None,
) -> bytes: ...
def sign_internal(
    parameter_set: str, sk: bytes, message: bytes, rand: bytes | None = None
) -> bytes: ...
def verify(
    parameter_set: str, pk: bytes, message: bytes, signature: bytes, context: bytes = b""
) -> bool: ...
def verify_internal(parameter_set: str, pk: bytes, message: bytes, signature: bytes) -> bool: ...
