"""ZF FROST (frost-secp256k1-tr) binding. Values are the crate's serialized bytes; maps are keyed
by participant identifier (1..n)."""

def ciphersuite_id() -> str: ...
def dkg_part1(identifier: int, max_signers: int, min_signers: int) -> tuple[bytes, bytes]: ...
def dkg_part2(
    secret1: bytes, round1_packages: dict[int, bytes]
) -> tuple[bytes, dict[int, bytes]]: ...
def dkg_part3(
    secret2: bytes, round1_packages: dict[int, bytes], round2_packages: dict[int, bytes]
) -> tuple[bytes, bytes]: ...
def group_public_key(public_key_package: bytes) -> bytes: ...
def taproot_output_key(public_key_package: bytes) -> bytes: ...
def commit(key_package: bytes) -> tuple[bytes, bytes]: ...
def signing_package(commitments: dict[int, bytes], message: bytes) -> bytes: ...
def signing_package_message(signing_package: bytes) -> bytes: ...
def sign(
    signing_package: bytes, nonces: bytes, key_package: bytes, taproot: bool = False
) -> bytes: ...
def aggregate(
    signing_package: bytes,
    shares: dict[int, bytes],
    public_key_package: bytes,
    taproot: bool = False,
) -> bytes: ...
